services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: crud
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: ./server
    image: server
    volumes:
      - $HOME/nodeapp:/code
    ports:
      - 4000:4000
    expose:
      - 4000
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: crud
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
      SERVER_PORT: 4000
    depends_on:
      - mysqldb
    networks:
      - internalnet

  reactapp:
    container_name: reactappcontainer
    build: ./client # Assuming your React app source code is in the "client" directory
    image: reactapp
    volumes:
      - $HOME/client:/app # Adjust this path if necessary
    ports:
      - 3000:3000 # Adjust the port as needed
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
